### ISSUE TITLE
Add support for more fields

### ISSUE THREAD

**Issue by cjpatton** [abetterinternet/libprio-rs#10]
This implementation of Prio supports a single, 32 bit field.The [design of "Prio v3"](https://github.com/abetterinternet/prio-documents/blob/main/design-document.md) calls for the implementation of more, larger fields, where the size of the field may depend on the application. This issue is intended to track the development of finite field arithmetic for additional fields.

There are two approaches we may consider at this stage:
(1) Add support for generic FF arithmetic that is suitable for all parameters we might consider for Prio.
(2) Pick a handful of fields and develop optimized code for each.

Option (2) will eventually be needed in the long term. However, option (1) offers several advantages for the medium term. First and foremost, developing optimized code now will incur a high cost later if we end up needing to change the parameters.

My coworker, @armfazh, has developed a generic implementation for fields with a prime modulus of size < 2^126. This code is written in Go; we hope to be able to release it soon. In the meantime, I'd like us to consider whether porting his code into Rust is the best path forward for the medium term.

Here are some benchmarks for that code.
```
goos: linux
goarch: amd64
BenchmarkFp/1/Add-8         	302270450	         3.89 ns/op
BenchmarkFp/1/Sub-8         	368558247	         3.29 ns/op
BenchmarkFp/1/Mul-8         	148488744	         8.00 ns/op
BenchmarkFp/1/Inv-8         	  783758	      1492 ns/op
BenchmarkFp/9/Add-8         	308265258	         3.90 ns/op
BenchmarkFp/9/Sub-8         	365978109	         3.27 ns/op
BenchmarkFp/9/Mul-8         	149422360	         7.93 ns/op
BenchmarkFp/9/Inv-8         	  521503	      2262 ns/op
```
The first set of benchmarks are for GF(3 * 2^30  + 1) and the second set of benchmarks are for GF(7 * 2^120 + 1). Inversion is slow because we just do x^-1 = x^(p-2) (mod p) instead of using extended Euclid as libprio-rs does now. (We do this so that inversion is constant time.) I don't think this is much of a problem though, since modular inversion is rarely on the critical path for Prio. (In any case, we will eventually do better with optimized code.) Note that the runtime for the other operations is about the same, regardless of the field size. This is because the code represents field elements the same way, using a pair of `uint64`'s.

Running this code with my own Prio implementation, I get the following proof generation/verification time for a length-1000 bit-vector (the proof is based on the SIMD circuit described in Theorem 5.3 of the CRYPTO 2019 paper):
```
BenchmarkProve/1/PRShortVector-8        	     631	   1883595 ns/op
BenchmarkVerif/1/PRShortVector-8        	    3086	    403487 ns/op
```
Proof generation takes just under 2ms and verification takes well under 1ms. (It should be even faster in Rust.)

**Comment by cjpatton** [comment]
FWIW, my vote would be for Option (2) and port @armfazh's code.

**Comment by acmiyaguchi** [comment]
I'm also in favor of (1) and a portable Rust implementation. It'd be nice to be able to bind to Python or Javascript early in the implementation process.

Do optimizations for specific fields typically involve more architecture-specific code (e.g., word alignment) or mathematical tricks?

**Comment by cjpatton** [comment]
> Do optimizations for specific fields typically involve more architecture-specific code (e.g., word alignment) or mathematical tricks?

My understanding is that it involves a bit of both :) Eventually we'll want a subject matter expert to chime in. For the moment, I feel competent enough to port the aforementioned code into Rust. A PR is forthcoming.

**Comment by cjpatton** [comment]
Good news, everyone! The underlying implementation of the FF arithmetic now supports GF(p) for any p < 2^126. The next step will be to add support for additional field parameters. @tgeoghegan proposed we do this by making `Field` a trait that specifies its own parameters (now `FieldParameters`; see `src/fp.rs`) and implements the various arithmetic operators we'll need. In particular, `pub struct Field(u128)` would become (something like)
```rust
pub trait Field {
    type Elem;

    fn field_parameters(self) -> &FieldParameters;
    fn get_value(self) -> Elem;
    ...
}
```
and the implementation of, e.g., `std::ops::Add` for `Field`, would  become (something like)
```rust
impl std::ops::Add for Field {
  fn add(self, rhs: Self) -> Self {
        Self(Self::field_parameters().add(self.get_value(), rhs.get_value())) 
    }
}
```
Then a concrete implementation of GF(2^32 - 2^20 + 1) would be expressed as (something like)
```rust
pub struct SmallField(u128);

impl Field for SmallField {
    type Elem = u128;

    fn field_parameters(self) -> &FieldParameters{
        &SMALL_FP
    }
    fn get_value(self) -> SmallField::Elem {
        self.0
    }
    ...
}
```
In addition to the field parameters, the `Field` implementation will also need to specify its own FFT parameters (currently hard-coded as `GENERATOR` and `N_ROOTS`).

Does anyone object to this plan?

**Comment by cjpatton** [comment]
The implementation ended up going a bit differently than expected. It uses a macro to generate boilerplate code: https://github.com/abetterinternet/libprio-rs/pull/16

**Comment by cjpatton** [comment]
The last step will be to replace `Field` with a trait bound `<F: FieldElement>` throughout the code.

**Comment by cjpatton** [comment]
TODOs added in the code:
* Rename `Field` to `Field32` once refactoring is done
* Generalize encoding of field elements as byte strings to support fields larger than 32 bits.
