### ISSUE TITLE
Make VDAF structs opaque to clients

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/libprio-rs#176]
The VDAF traits define a number of associated types (input shares, prepare messages, prepare step, aggregate shares, etc.) that are emitted and consumed by VDAF implementations. Clients of crate `prio` have no reason to examine the fields of these structs, much less mutate them. To minimize the risk of client error invalidating PPM/VDAF's security guarantees, we should make these as opaque as possible. At a minimum, we should audit the existing messages and make all their fields private or `pub(crate)` at most. It'd also be nice if we could somehow enlist the compiler or some other automation to make sure we don't accidentally make fields public in the future.

**Comment by divergentdave** [comment]
I don't think there's any feature in the compiler to deny `pub` fields (short of writing our own attribute procedural macro), and a quick look at the Clippy lints didn't turn up anything relevant. I think it's just up to us to not make them `pub`.
