### ISSUE TITLE
Support for uints, floats (and differential privacy)

### ISSUE THREAD

**Issue by degregat** [abetterinternet/libprio-rs#9]
Is there interest to support types that are not booleans?

There is support in libprio for b-bit uints, which needed [changes in the server code to not leak individual bits](https://github.com/mozilla/libprio/pull/96/files?file-filters%5B%5D=.c#diff-45f5ff6b7efbabeb446dfc1feffc39caa3b1766ec537ddc0c135bce8727c3767R121), and changes on the client side to [encode uints as bit vectors](https://github.com/mozilla/libprio/pull/96/files?file-filters%5B%5D=.c#diff-b9bdafd0b29db52dfbf02751be702793114f261de2054f3519a068e9ea6dc262R339). It can be found here: https://github.com/mozilla/libprio/pull/96

There is an (open) PR which can wrap a prio implementation supporting uints to give support for a signed fixed-point encoding to approximate floats: https://github.com/mozilla/libprio/pull/108

I am also working on adding support for differential privacy: https://github.com/mozilla/libprio/issues/76

These two extensions would make it intersting for differentially private sum statistics and especially as a backend for [federated learning](https://en.wikipedia.org/wiki/Federated_learning).

I am happy to answer any questions regarding uints, but most likely wont be able to schedule any actual coding time until early 2021.

Since fixed-point encoding and differential privacy are mostly independent and can wrap a library given it supports uints, we decided an external library would make most sense. I'll start one, and if it is based on libprio-rs port the fixed-point C code as time permits. I am also open to suggestions on how to minimize friction on that one.

Thanks for this taking on this effort, it looks great so far and I'm looking forward to contribute to it!

**Comment by tgeoghegan** [comment]
We are pretty exclusively focused right now on enabling our first use case for Prio, and anticipate that our eventual, more general Prio service will be radically different from what we've built and deployed in the fall and winter of 2020. So I can't tell you what our plans are for the kinds of features you're talking about, because we have no plan yet!

**Comment by degregat** [comment]
Totally understand, thanks for the update! I'll continue as planned then, keeping an eye on modularity. If your endeavor has consolidated a bit more next year, we can check again wether merging efforts makes sense. All the best until then :)

**Comment by degregat** [comment]
Looks like #23 will provide a more general approach to solve this problem.
