### ISSUE TITLE
Naming conventions for `Value` implementations, plus new types

### ISSUE THREAD

**Issue by cjpatton** [abetterinternet/libprio-rs#94]
Module `pcp::types` defines the following types:
* `Boolean` -- each input is 1 or 0; the aggregate output is the total.
* `PolyCheckedVector` -- the input is a vector of field elements, where for each element `x`, we have `p(x)==0` for some polynomial `p`. The output is the sum of the input vectors, element-wise. Basically, this is a generalization of a vector of `Boolean`s.
* `MeanVarUnsignedVector` -- the input is a vector of integers in range `[0, 2^n)` for some `n`. The output of the sum of these vectors, as well as the sum of the squares of each element.

We came up with these types in a fairly ad-hoc manner. Basically each demonstrates some aspect of the proof system that we wanted to prototype. Now that we're farther along, I think it's time we settle on the types we actually want to use and to normalize the names.

First, I'd like to suggest the following convention for naming types: The name of the type should reflect the type of the *aggregate* rather than the inputs. For instance, we would rename `Boolean` to `Count`.

Here are the types I think we want to start:
* `Count` -- an 0 or a 1. (This would replace `Boolean`.)
* `CountVec` -- a vector of 0s and 1s. (This would replace `PolyCheckedVector` -- I don't think we have any need for the generalization.)
* `Sum` -- an integer in range `[0,2^n)` for some `n`.
* `SumVec` -- a vector of integers in range `[0, 2^n)` for some `n`.
* `Histogram` -- an entry in a histogram with fixed bucket boundaries. Similar to https://prometheus.io/docs/concepts/metric_types/#histogram.

The reason we want the `Vec` variant of things is that, when we have many instances of the same type, it can be more efficient to encode them all together.

**Comment by tgeoghegan** [comment]
I think all these are sound!

- Do you have any ideas on what `Histogram` looks like? My intuition is that if the task definition includes fixed bucket boundaries, an individual measurement can be represented as the index of the bucket where the measurement occurs, and then the same proof system as `Sum` can be used since the measurement is just an integer?
- Why not `SumSquared` (which I noticed in an earlier edit of this issue)? I thought that would be necessary if a collector wanted to compute a standard deviation.

**Comment by cjpatton** [comment]
* For histogram I was thinking of doing something analogous to Prometheus: https://prometheus.io/docs/practices/histograms/. Basically the measurement is an arbitrary number, and the aggregate result would be a histogram with pre-defined buckets.
* I removed `SumSquared` because I didn't want to scope-creep this issue. I figured we could add this later.
